### ISSUE TITLE
the example playbook has wrong attribute "name" under "users"

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-uchiwa#14]
##### ISSUE TYPE
 - Bug Report

##### ROLE VERSION

```
1.1.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY

according to [the doc](https://docs.uchiwa.io/getting-started/configuration/), the attribute for user name under `users` is `username`, not `name`. the example playbook should be updated.

##### STEPS TO REPRODUCE

set the following variable and run playbook.

```yaml
uchiwa_config:
  sensu:
    - name: staging
      host: 192.168.165.111
      port: 4567
  uchiwa:
    host: 0.0.0.0
    port: 3000
    users:
      - name: admin
        password: password
        # openssl rand -base64 40 |  tr -- '+=/' '-_~'
        accessToken: vFzX6rFDAn3G9ieuZ4ZhN-XrfdRow4Hd5CXXOUZ5NsTw4h3k3l4jAw__
        readonly: false
      - name: guest
        password: password
        accessToken: hrKMW3uIt2RGxuMIoXQ-bVp-TL1MP4St5Hap3KAanMxI3OovFV48ww__
        readonly: true
```

##### EXPECTED RESULTS

user `admin` should be able to login.

##### ACTUAL RESULTS

it is not.
